# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rubocop/rake_task'
require 'rspec/core/rake_task'

desc 'Default: run tests'
task default: %i[spec]

RSpec::Core::RakeTask.new(:spec)
