require: 
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - '**/Gemfile'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/spec/**/*'
    - '**/templates/**/*'
    - '**/bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Exclude:
    - lib/kiqr.rb
Layout/LineLength:
  Max: 150
  Exclude: