inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - '**/spec/dummy/**/*'
    - '**/templates/**/*'
RSpec/ImplicitExpect:
  EnforcedStyle: should