inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - '**/spec/rails_app/**/*'
    - '**/templates/**/*'
    - '**/migrate/**'
    - '**/gem_version.rb'

RSpec/ImplicitExpect:
  EnforcedStyle: should
Metrics/BlockLength:
  Exclude:
    - tasks/**/*